# Generated by Django 3.2.1 on 2021-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0039_auto_20200331_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='abstract',
            field=models.TextField(blank=True, default='', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='post_text',
            field=models.TextField(blank=True, default='', verbose_name='text'),
        ),
    ]
